-- Add specification workflow types to memory_type constraint
-- Migration: 014
-- Date: 2025-11-02
--
-- This migration documents the addition of six new memory types for specification workflow:
-- - constitution: Project principles and quality gates
-- - feature_spec: Feature specifications with user scenarios
-- - implementation_plan: Technical architecture and design
-- - task_breakdown: Task lists with dependencies
-- - quality_checklist: Validation and acceptance criteria
-- - clarification: Resolved ambiguities in specs
--
-- Note: LibSQL/SQLite does not support ALTER TABLE ... MODIFY COLUMN for CHECK constraints.
-- The constraint modification was made directly to 001_initial_schema.sql since
-- this change is being made before initial production deployment.
--
-- For existing production databases (if any), manual migration would require:
-- 1. Create new table with updated constraint
-- 2. Copy all data from old table
-- 3. Drop old table
-- 4. Rename new table
--
-- Since we modified the initial schema before production deployment,
-- this migration serves as documentation only.

SELECT 'Migration 014: specification workflow types added to schema' AS note;
