# Cargo build configuration for Mnemosyne

[build]
# Incremental compilation for faster dev builds
# (Automatically disabled for release builds with LTO)
incremental = true

# Note: Parallel compilation is enabled by default
# To limit jobs: use CARGO_BUILD_JOBS environment variable

[profile.dev]
# Explicit incremental compilation for development
incremental = true
# Fast compilation, minimal optimization
opt-level = 0
# Disable debug info for faster builds (use "line-tables-only" if needed)
debug = false

[profile.dev.build-override]
# Optimize build scripts even in dev mode
opt-level = 3

[profile.release]
# Inherits from Cargo.toml:
# - opt-level = 3
# - lto = true
# - codegen-units = 1
# Incremental automatically disabled due to LTO

# Fast release build for testing (not for production)
[profile.fast-release]
inherits = "release"
lto = "thin"           # Thin LTO instead of full LTO (much faster)
codegen-units = 16     # Parallel codegen (faster builds)
incremental = true     # Enable incremental compilation
opt-level = 2          # Good optimization, faster than opt-level = 3

# Environment variable hints for faster builds
[env]
# Use system LLVM linker if available (faster than default)
# Uncomment based on your system:
# RUSTFLAGS = "-C link-arg=-fuse-ld=lld"  # Linux with lld
# RUSTFLAGS = "-C link-arg=-fuse-ld=mold" # Linux with mold (fastest)
